version: '3.9'

services:
  frontend:
    build: ./newscraper-react
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app-network

  backend:
    build: ./
    expose:
      - '8000'
    networks:
      - app-network

networks:
  app-network:
