fossforce.com:
  name: FOSSScraper
  base_url: https://fossforce.com/

miamammausalinux.org:
  name: MMULScraper
  base_url: https://www.miamammausalinux.org/

bleepingcomputer.com:
  name: BleepingComputer
  base_url: https://www.bleepingcomputer.com

redhotcyber.com:
  name: RedHotCyber
  base_url: https://www.redhotcyber.com